version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    target-branch: "upstream-master-depbot"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1000
