site_name: WAL-G
nav:
    - Overview: README.md
    - Foundation DB: FoundationDB.md
    - Mongo DB: MongoDB.md
    - MySQL: MySQL.md
    - PostgreSQL: PostgreSQL.md
    - SQLServer: SQLServer.md
    - Windows: Windows.md
theme: readthedocs
