# Configures dependabot dependency updates
# For details, see: https://dependabot.com/docs/config-file/
version: 1
update_configs:
  - package_manager: "go:dep"
    directory: "/"
    update_schedule: "daily" #should be weekly, testing
    version_requirement_updates: "increase_versions"
